
import AppProvider from "@/provider/AppProvider";
import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
// import ProtectedRoute from "@/components/auth/ProtectedRoute";

export const metadata: Metadata = {
  title: "Psykick Club",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#36007B] text-white dashboard-body">
        {/* <ProtectedRoute> */}
        <AuthProvider>
        <div className="backdrop-blur-sm bg-[#371B77]/40 dashboard-shadow">
          <main className="">
           <AppProvider>
            {children}
            </AppProvider> 
          </main>
        </div>
        </AuthProvider>
        {/* </ProtectedRoute> */}
      </body>
    </html>
  );
}
