import { Sidebar } from "@/components/dashboard/SideBar";
import "../globals.css";
import type { Metadata } from "next";
import { AdminDashboardTabsList } from "@/data/data";
import Header from "@/components/dashboard/dashboard-header";
// import ProtectedRoute from "@/components/auth/ProtectedRoute";

export const metadata: Metadata = {
  title: "Psykick Club",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#36007B] text-white dashboard-body">
        {/* <ProtectedRoute> */}
          <Sidebar lists={AdminDashboardTabsList} />
          <div className="px-4 md:ml-[272px] backdrop-blur-sm bg-[#371B77]/40 dashboard-shadow">
            <Header />
            {children}
          </div>
        {/* </ProtectedRoute> */}
      </body>
    </html>
  );
}
