import Header from "@/components/_dashboard/dashboard-header";
import { Sidebar } from "@/components/_dashboard/SideBar";
import { AdminDashboardTabsList } from "@/data/data";
import AppProvider from "@/provider/AppProvider";
import type { Metadata } from "next";
import "../globals.css";
// import ProtectedRoute from "@/components/auth/ProtectedRoute";

export const metadata: Metadata = {
  title: "Psykick Club",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#36007B] text-white dashboard-body">
        {/* <ProtectedRoute> */}
        <Sidebar lists={AdminDashboardTabsList} />
        <div className="px-4 md:ml-[272px] backdrop-blur-sm bg-[#371B77]/40 dashboard-shadow">
          <Header />
          <main className="">
            <AppProvider>{children}</AppProvider>
          </main>
        </div>
        {/* </ProtectedRoute> */}
      </body>
    </html>
  );
}
